# Generated by Django 3.2.15 on 2022-10-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='experience',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
